apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: helloworldwebapp
spec:
 replicas: 1
 template:
  metadata:
   labels:
    app: helloworldwebapp
  spec:
   containers:
   - name: helloworldwebapp
     image: acrdemoeastus.azurecr.io/helloworldweb:v1
     ports:
     - containerPort: 8888
   imagePullSecrets:
   - name: acr-auth
---
apiVersion: v1
kind: Service
metadata:
 name: helloworldwebapp
spec:
 type: LoadBalancer
 ports:
 - port: 80
 selector:
  app: helloworldwebapp

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: helloworldservice
spec:
 replicas: 1
 template:
  metadata:
   labels:
    app: helloworldservice
  spec:
   containers:
   - name: helloworldservice
     image: acrdemoeastus.azurecr.io/helloworldservice:v1
     ports:
     - containerPort: 5555
   imagePullSecrets:
   - name: acr-auth
---
apiVersion: v1
kind: Service
metadata:
 name: helloworldservice
spec:
 type: LoadBalancer
 ports:
 - port: 80
 selector:
  app: helloworldservice

